## Synthetic population pipeline for Freight Île-de-France
## based on the synpp package

# This is the path to a directory where the pipeline can store temporary data
working_directory: D:/MATSim_egt2018/cache_egt2018

# This section defines which parts of the pipeline should be run
run:
#  - synthesis.output # To create the output population in the output_path (see below)
  - data.hts.egt_2018.filtered

# These are configuration options that we use in the pipeline starts
config:
  # Some general configuration
  processes: 10

  # Define sampling rate and random seed for the output population
  sampling_rate: 0.001
  random_seed: 1234

  # Paths to the input data and where the output should be stored
  data_path: D:/L_MATSim_IdF/data
  output_path: D:/MATSim_egt2018/output_egt2018
